async:
    dao:
     mapperLocations: /mapper
     basePackages: com.tg.mapper
     username: root
     host: localhost
     port: 3306
     password: admin
     database: test
     authenticationPlugin: caching_sha2_password
     sslMode: disabled
     maxTotal: 12
     maxWaitMillis: 10000



